---
ID: "34de6aff-9ef4-40db-a24b-ebfd4170179f"
Parent: "54f89e61-6008-4130-b6d9-3f4c5fdc447b"
Template: "fe5dd826-48c6-436d-b87a-7c4210c7413b"
Path: "/sitecore/media library/Project/retail/forma-lux/Products"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251008T144042Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\sanduni.galagoda@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\sanduni.galagoda@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c7d87621-530e-4613-8a64-4fe45e6621ec"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sanduni.galagoda@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251008T144042Z
