---
ID: "4d2f530e-4300-458a-90c8-a551eed5a865"
Parent: "165f9c88-a72a-417e-b8b9-12b1df70a1e8"
Template: "165f9c88-a72a-417e-b8b9-12b1df70a1e8"
Path: /sitecore/templates/Project/retail/Components/Products/All Products Carousel/Rendering Parameters/All Products Carousel Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c8a8d8f6-4088-463c-b1d3-821d70120abb"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\movin.tilakaratne@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250923T130825Z
