---
ID: "be840b36-76a1-468a-8384-fad1ba4b5bcd"
Parent: "99d7de86-e1ea-4759-9aa6-8a0afc72a898"
Template: "99d7de86-e1ea-4759-9aa6-8a0afc72a898"
Path: /sitecore/templates/Project/retail/Components/Articles/Article Carousel/Rendering Parameters/Article Carousel Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f96d85c8-ff14-49a1-8201-32f009c4ac8b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\isuru.bandara@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250917T105653Z
