---
ID: "53f575c0-5845-4e2c-bfa6-ce36816528dc"
Parent: "4dc88d14-f1ca-48bd-808b-94a69555a9ff"
Template: "4dc88d14-f1ca-48bd-808b-94a69555a9ff"
Path: "/sitecore/templates/Project/travel-hospitality/Footer/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {4DC88D14-F1CA-48BD-808B-94A69555A9FF}
    {58C335EB-251B-4EE5-BC3F-11D8F4C41240}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "ae48cdf4-14dd-4b24-aed9-b697aea925f2"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "204c21db-d29a-4108-9322-62a2cf5a4145"
      Hint: Title
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250728T215110Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6083f854-8afb-483c-bec6-f54b616a8067"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\johannes.zijlstra@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250807T190234Z
